# Generated by Django 3.0.4 on 2020-04-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.FloatField(default=7.7),
        ),
    ]
