 # Generated by Django 3.0.4 on 2020-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0002_auto_20200426_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
