# Generated by Django 3.0.4 on 2020-04-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0004_remove_anime_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
